### ISSUE TITLE
3주차 피드백 반영

### ISSUE THREAD

**Issue by Dockerel** [kakao-tech-campus-2nd-step3/Team5_BE#18]
## 💡 Issue

---

### ✏️ Description

---

### ✅ To-do List

---
- [x] 유튜브 url validation 구체화
- [x] dto record로 통일
- [x] 상수 static으로 관리
- [x] WebClient Timeout 지정 및 bean 등록 후 사용. 재사용을 위한 get 요청 커스텀 및 분리
- [x] 커스텀 record + ObjectMapper로 코드 개선
- [x] WireMock으로 외부 api 테스트 작성
