### ISSUE TITLE
좋아요 기능 3주차 피드백 반영

### ISSUE THREAD

**Issue by xkrwjdals** [kakao-tech-campus-2nd-step3/Team5_BE#20]
### ✏️ Description

3주차 코드 리뷰 피드백 반영

### ✅ To-do List

---
- [x] 엔티티 데이터 타입, `long `-> `Long`, `int` -> `Integer` 로 변경, membership 변수는 enum 으로 관리
- [x] setter 삭제, 생성자로 변경
- [x] 일단 좋아요 기능을 Video Entity 의 likeCount 변수로 관리
