### ISSUE TITLE
영상 자막 추가 + 영상 비율 조절 외부 api 설계

### ISSUE THREAD

**Issue by Dockerel** [kakao-tech-campus-2nd-step3/Team5_BE#46]
## 💡 Issue
영상 자막 추가 + 영상 비율 조절 외부 api 설계

---

### ✏️ Description
영상 자막 추가
* faster-whisper
* fastapi
영상 비율 조절
* ffmpeg + subprocess

#### 작업 링크
https://github.com/Dockerel/subtitle_adder

---

### ✅ To-do List

---
- [x] 영상 추출
- [x] 영상 오디오 파일 추출
- [x] 자막 추출
- [x] 자막 입히기
- [x] s3에 저장
- [x] smtp로 유저에게 완료 메일 전송
- [x] 영상 resize(비율 맞추기)
- [x] 배포
    - [x] vast.ai + ngrok 배포
    - [x] ffmpeg + cuda 설정
    - [x] whisper + cuda 설정

**Comment by Dockerel** [comment]
https://github.com/Dockerel/subtitle_adder

완료하였습니다.
