### ISSUE TITLE
추천 알고리즘 환경 세팅

### ISSUE THREAD

**Issue by anaconda77** [kakao-tech-campus-2nd-step3/Team5_BE#62]
## 💡 Issue

---
- 추천 알고리즘을 구현할 파이썬 환경 세팅과 db로 활용할 Redis 초기 설정 작업을 진행합니다.
### ✏️ Description

---
- pipenv 가상 환경에 fastapi, redis 등 패키지를 관리합니다.
- redis 설정 및 필요한 스키마를 정의합니다. (영상 정보, 유저 이벤트 정보, 추천 알고리즘에 의해 계산된 스코어 정보)
- 요청 처리의 효율성을 위해 멘토님이 피드백에서 말씀해주신 스케줄러를 구현해볼 예정입니다.
- 추천 알고리즘 함수는 추후 다른 분(영진 님)이 설계한 코드를 받아올 예정입니다.
- 모든 작업 사항들은 개인 레포지토리에서 지속적으로 관리할 예정입니다.
https://github.com/anaconda77/recommend-algorithms
- API 구현은 일단 다음 이슈로 넘겨 처리할 예정입니다.

### ✅ To-do List

---
- [x] pipenv fastAPI 환경 구성
- [x] redis 초기 설정
- [x] 받아온 추천 알고리즘 적용
- [x] 요청 스케줄러 구현
