### ISSUE TITLE
조회수/좋아요 및 추천 알고리즘 API 구현

### ISSUE THREAD

**Issue by anaconda77** [kakao-tech-campus-2nd-step3/Team5_BE#72]
## 💡 Issue

---
- 완성된 추천 알고리즘을 기반으로 데이터를 주고받을 수 있도록 API를 구현합니다.
- 기존 조회수/좋아요를 저장했던 Repository를 RDB에서 Redis(NoSQL)로 이전합니다.

### ✏️ Description

---
- 스프링 부트 서버와 FastAPI 서버가 직접적으로 통신하지 않고 Redis를 중간 매개체로 요청/응답 메커니즘을 구현합니다.
- 스프링 부트 <-> Redis: 좋아요/조회수 쓰기/읽기(작업 큐에 add), 추천 영상 리스트 읽기
- FastAPI 서버 <-> Reidis: 좋아요/조회수 읽기, 추천 알고리즘 실행 후 추천 영상 리스트 갱신

### ✅ To-do List

---
- [x] 스프링 부트 Redis 설정
- [x] 조회수/좋아요 정보 Repository Redis 이전
- [x] 도커 파일 설정
- [x] 추천 알고리즘 서비스 메서드 구현
- [x] Redis TestContainer 설정(도커 실행 필요)
~~- [ ] 동시성 문제 해결(다음 이슈로 처리)~~
