### ISSUE TITLE
하이라이트 추출

### ISSUE THREAD

**Issue by xkrwjdals** [kakao-tech-campus-2nd-step3/Team5_BE#81]
## 💡 Issue

---
> 이슈에 대한 간략한 설명

### ✏️ Description

---
> 작업 내용에 대한 상세한 설명(스크린샷 첨부 가능)

### ✅ To-do List

---
- [x] 하이라이트 추출 프롬포트 수정 (카테고리별 -> 구간 별 + 1분 추출)
- [x] 하이라이트 추출 .py 파일 모듈화 
- [x] 기존의 script_extractor 에서 동작할 수 있도록 코드 추가
- [x] vast.ai 클라우드 서버 환경에서 FastAPI 앱 실행 테스트
- [x] 하이라이트 영상 5개 중 하나를 선택하는 api 구현 및 관련 사항 로직 수정
- [x] vast.ai 서버 배포
